# Generated by Django 5.2.6 on 2025-09-15 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=20, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo_classe', models.CharField(max_length=50)),
                ('exame_combinado', models.BooleanField(default=False)),
                ('nota_maxima', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='CriterioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=20)),
                ('aprovacao_reprovacao', models.CharField(max_length=100)),
                ('nota_minima', models.FloatField()),
                ('nota_maxima', models.FloatField()),
                ('nota_positiva_aprovacao', models.FloatField()),
                ('incluir_exame', models.BooleanField(default=False)),
                ('sistema_recursos', models.BooleanField(default=False)),
                ('formula', models.CharField(blank=True, max_length=200)),
                ('percentagem_trimestre1', models.FloatField(default=33.33)),
                ('percentagem_trimestre2', models.FloatField(default=33.33)),
                ('percentagem_trimestre3', models.FloatField(default=33.33)),
                ('percentagem_prova_final', models.FloatField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Critério de Avaliação',
                'verbose_name_plural': 'Critérios de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/')),
                ('relacionamento', models.CharField(max_length=50)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('morada', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Encarregado',
                'verbose_name_plural': 'Encarregados',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/')),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('morada', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('peso', models.FloatField(default=0)),
                ('formula', models.CharField(blank=True, max_length=200)),
                ('dia', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
            },
        ),
        migrations.CreateModel(
            name='SalaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sala de Aula',
                'verbose_name_plural': 'Salas de Aula',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('perfil', models.CharField(choices=[('Admin', 'Admin'), ('Professor', 'Professor'), ('Aluno', 'Aluno'), ('Encarregado', 'Encarregado')], max_length=50)),
                ('senha', models.CharField(max_length=128)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/')),
                ('nome_pai', models.CharField(blank=True, max_length=100)),
                ('nome_mae', models.CharField(blank=True, max_length=100)),
                ('hablitacoes', models.CharField(blank=True, max_length=100)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('Cedula', 'Cédula'), ('BI', 'Bilhete de Identidade')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10)),
                ('estado_civil', models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Outro', 'Outro')], max_length=20)),
                ('curso', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('morada', models.CharField(blank=True, max_length=200)),
                ('data_inscricao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Transferido', 'Transferido')], default='Ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('classe_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classe')),
                ('encarregado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encarregado')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='PlanoPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
            ],
            options={
                'verbose_name': 'Plano Pedagógico',
                'verbose_name_plural': 'Planos Pedagógicos',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('trimestre', models.CharField(choices=[('1º Trimestre', '1º Trimestre'), ('2º Trimestre', '2º Trimestre'), ('3º Trimestre', '3º Trimestre')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prova')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=100)),
                ('turno', models.CharField(choices=[('Manha', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=20)),
                ('numero_alunos', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anoletivo')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classe')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salaaula')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('escola_destino', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('classe_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classe')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
            },
        ),
        migrations.CreateModel(
            name='ProfessorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'verbose_name': 'Professor-Turma',
                'verbose_name_plural': 'Professores-Turmas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='materiais/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma'),
        ),
    ]
