# Generated by Django 5.2.6 on 2025-09-17 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('diretor', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.RenameModel(
            old_name='Transferencia',
            new_name='EscolaTransferencia',
        ),
        migrations.AlterModelOptions(
            name='escolatransferencia',
            options={'verbose_name': 'Escola de Transferência', 'verbose_name_plural': 'Escolas de Transferência'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='risco_reprovacao',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto')], default='Baixo', max_length=20),
        ),
        migrations.AddField(
            model_name='nota',
            name='modalidade',
            field=models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa'), ('Nacional', 'Nacional')], default='Interna', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='reapreciacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nota_maxima',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='criterioavaliacao',
            name='nota_maxima',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='criterioavaliacao',
            name='nota_minima',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='criterioavaliacao',
            name='nota_positiva_aprovacao',
            field=models.FloatField(default=10),
        ),
        migrations.CreateModel(
            name='ExameEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Recurso', 'Recurso'), ('Extraordinario', 'Extraordinário'), ('Equivalencia', 'Equivalência'), ('Melhoria', 'Melhoria')], max_length=50)),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Exame Especial',
                'verbose_name_plural': 'Exames Especiais',
            },
        ),
    ]
